# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop

variables:
  major: 1
  minor: 1

name: $(major).$(minor)$(Rev:.r)

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  workingDirectory: $(Build.SourcesDirectory)/inlook_app
  displayName: 'npm install and build'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure dla studentów (80a1d7ce-101f-4397-80d8-632541f4a513)'
    appType: 'webAppLinux'
    WebAppName: 'Inlook23'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'