# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop
- feature/deploy

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  major: 1
  minor: 1

name: $(major).$(minor)$(Rev:.r)

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Tests'
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: efcore-migration-script-generator-task@0
  displayName: 'EF migration artifact'
  inputs:
    installdependencies: true
    projectpath: '$(Build.SourcesDirectory)/Inlook_Infrastructure/Inlook_Infrastructure.csproj' 
    databasecontexts: 'Inlook_Context'
    startupprojectpath: '$(Build.SourcesDirectory)/Inlook_API/Inlook_API.csproj'
    targetfolder: '$(build.artifactstagingdirectory)/migrations'

- task: PublishPipelineArtifact@1
  displayName: 'Publish migrations'
  inputs:
    targetPath: '$(build.artifactstagingdirectory)/migrations'
    artifact: 'migrations'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs: 
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: '_api'